### ISSUE TITLE
Graphql subscription issue on ws

### ISSUE THREAD

**Issue by shenbagapandian** [Al3nMicL/graphql-apollo-server-sub#1]
If my endpoint is **http://domain_url:4000/graphql**, then everything working fine.
And i changed my endpoint to **http://domain_url/graphql** then i'm facing issue like : **"Could not connect to websocket endpoint ws://domain_url/graphql. Please check if the endpoint url is correct."** . I'm using centOS for reverse proxy. Is anything needed for graphql subscription ?? kindly guide me for the subscription server setup ..

**Comment by Al3nMicL** [comment]
Hi @shenbagapandian 
I had this repo automatically created for me when I was testing out a code sandbox (see the url in the description), so I'm not sure of the particulars of the configuration.

Is suggest you try to open up the link and find the original sandbox where it was forked from. Perhaps the creator can point you in the right direction?
